#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# KMP / Cocoapods
# Speed up Android sync and avoid iOS CInterop work during Android-only builds
# Enable CInterop commonization so iosMain can see GoogleMaps cinterop
kotlin.mpp.enableCInteropCommonization=false
kotlin.mpp.enableCInteropCommonization.nowarn=false
# If configuration cache causes issues during plugin changes, disable it
org.gradle.configuration-cache=false