# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!
inhibit_all_warnings!

project 'DealSpot.xcodeproj'

target 'DealSpot' do
  # Kotlin Multiplatform module as a Pod
  pod 'ComposeApp', :path => '../composeApp'
  # Google Maps SDK for iOS
  pod 'GoogleMaps', '8.4.0'
  pod 'Google-Maps-iOS-Utils', '5.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end


